### ISSUE TITLE
Different values in different browsers?

### ISSUE THREAD

**Issue by birdsarah** [platfora/Canteen#2]
Hi! Wondering if you have any advice for us. We're planning on using Canteen for testing in Bokeh. It's awesome - thanks! 

We seem to be encountering very slightly different values in our arguments between different browsers. I'm assuming it's our code not Canteen but I was wondering if you'd come across this before / had any suggestions. 

The issue where we're looking at this is: https://github.com/bokeh/bokeh/pull/2726

Many thanks!

Sarah Bird

**Comment by ericdrowell** [comment]
Hi @birdsarah, I just took a look at your thread, and this definitely looks like a rounding problem somewhere in your code, because the values are actually pretty off:

![bokeh](https://cloud.githubusercontent.com/assets/1498774/9359863/f52a6650-4647-11e5-9402-b99204a0c822.png)

with a variance of between 0.01 and 0.03.  Now, in different browsers, some math constants like PI have slightly different values, but the variances are incredibly marginal, like 0.0000001.  

Here are a few approaches that you could take:

1) determine where the rounding variances are occurring in your code, and make changes such that the end results are fairly uniform across browsers (e.g. perhaps you are multiplying the value of PI to some values thousands of times, causing a wide variance in the end result)

2) Canteen automatically rounds values to the nearest 1/1000th decimal point to cover slight rounding variances between browsers.  This variable is set in canteen.js here:

var NUMBER_PRECISION = 1000;

you could change this value to something smaller, like 1.

3) If you can get away with loose comparisons over strict ones (i.e. you just care if the right methods are called and the right properties are set, regardless of the values) you can do:

var hash = context.hash({
  loose: true
});

Also, it feels pretty clear to me that the rounding accuracy should be configurable, so I'll make a change that enables that for cases like yours, where you might want to say, always round to the nearest whole integer.

Is any of these useful?

**Comment by ericdrowell** [comment]
Hi @birdsarah, I just took a look at your thread, and this definitely looks like a rounding problem somewhere in your code, because the values are actually pretty off:

![bokeh](https://cloud.githubusercontent.com/assets/1498774/9359863/f52a6650-4647-11e5-9402-b99204a0c822.png)

with a variance of between 0.01 and 0.03.  Now, in different browsers, some math constants like PI have slightly different values, but the variances are incredibly marginal, but something like 0.0000001.  

There are two approaches that I would suggest taking:

1) determine where the rounding variances are occurring in your code, and make changes such that the end results are fairly uniform across browsers (e.g. perhaps you are multiplying the value of PI to some values thousands of times, causing a wide variance in the end result)

2)

**Comment by ericdrowell** [comment]
An update on this: I went ahead and made that change, so now you can do things like:

var json = context.json({
  decimalPoints: 1
});

This will round all numeric values to 1 decimal point.  If you upgrade to 1.0.4 you'll get this addition.

**Comment by birdsarah** [comment]
Thanks so much for the quick response - we're taking a look now.

**Comment by ericdrowell** [comment]
No problemo!
